import { Vacancy, Resume, Company, JobSeeker, Application } from './types'

export const mockCompanies: Company[] = [
  {
    id: 'company-1',
    name: 'ТехКорп Решения',
    description: 'Ведущая компания разработки программного обеспечения. Мы создаем инновационные продукты для миллионов пользователей.',
    logo: '🏢',
    website: 'techcorp.ru',
    location: 'Москва',
    employee_count: 500,
    industry: 'IT',
    rating: 4.8,
    created_at: '2024-01-01',
    updated_at: '2024-02-16',
  },
  {
    id: 'company-2',
    name: 'Облачные Технологии',
    description: 'Лидер в сфере облачных вычислений и инфраструктурных решений.',
    logo: '☁️',
    website: 'cloudbase.ru',
    location: 'Санкт-Петербург',
    industry: 'Cloud',
    employee_count: 250,
    rating: 4.6,
    created_at: '2024-01-05',
    updated_at: '2024-02-16',
  },
  {
    id: 'company-3',
    name: 'ДатаВижн Аналитика',
    description: 'Решения на основе ИИ и машинного обучения для современного бизнеса.',
    logo: '📊',
    website: 'datavision.ru',
    location: 'Новосибирск',
    employee_count: 180,
    industry: 'AI/ML',
    rating: 4.7,
    created_at: '2024-01-10',
    updated_at: '2024-02-16',
  },
  {
    id: 'company-4',
    name: 'SecureNet Безопасность',
    description: 'Решения кибербезопасности и защиты данных',
    logo: '🔐',
    website: 'securenet.ru',
    location: 'Новосибирск',
    employee_count: 320,
    industry: 'Кибербезопасность',
    rating: 4.5,
    created_at: '2024-01-15',
    updated_at: '2024-02-16',
  },
  {
    id: 'company-5',
    name: 'DesignStudio Креатив',
    description: 'UI/UX дизайн и цифровое творчество',
    logo: '🎨',
    website: 'designstudio.ru',
    location: 'Екатеринбург',
    employee_count: 150,
    industry: 'Дизайн',
    rating: 4.9,
    created_at: '2024-01-20',
    updated_at: '2024-02-16',
  },
]

export const mockVacancies: Vacancy[] = [
  {
    id: 'vacancy-1',
    company_id: 'company-1',
    title: 'Старший React разработчик',
    description:
      'Ищем опытного React разработчика для нашей команды фронтенда. Вы будете разрабатывать масштабируемые веб-приложения с использованием современных технологий.',
    salary_min: 120000,
    salary_max: 160000,
    currency: 'RUB',
    location: 'Москва',
    employment_type: 'full_time',
    level: 'senior',
    status: 'active',
    applications_count: 12,
    views_count: 245,
    created_at: '2024-02-10',
    updated_at: '2024-02-16',
    deadline: '2024-03-10',
  },
  {
    id: 'vacancy-2',
    company_id: 'company-2',
    title: 'Облачный архитектор',
    description:
      'Проектирование и внедрение облачной инфраструктуры. Требуется опыт работы с AWS, Kubernetes и микросервисами.',
    salary_min: 140000,
    salary_max: 180000,
    currency: 'RUB',
    location: 'Санкт-Петербург',
    employment_type: 'full_time',
    level: 'senior',
    status: 'active',
    applications_count: 8,
    views_count: 189,
    created_at: '2024-02-12',
    updated_at: '2024-02-16',
    deadline: '2024-03-12',
  },
  {
    id: 'vacancy-3',
    company_id: 'company-3',
    title: 'Инженер Machine Learning',
    description:
      'Разрабатывайте и развертывайте ML модели для нашей AI платформы. Требуется опыт работы с Python, TensorFlow и обработкой данных.',
    salary_min: 130000,
    salary_max: 170000,
    currency: 'RUB',
    location: 'Москва',
    employment_type: 'full_time',
    level: 'mid',
    status: 'active',
    applications_count: 15,
    views_count: 312,
    created_at: '2024-02-08',
    updated_at: '2024-02-16',
    deadline: '2024-03-08',
  },
  {
    id: 'vacancy-4',
    company_id: 'company-4',
    title: 'Аналитик безопасности',
    description:
      'Присоединитесь к нашей команде безопасности для выявления и устранения угроз кибербезопасности. Предпочтительны сертификаты CISSP или CEH.',
    salary_min: 100000,
    salary_max: 140000,
    currency: 'RUB',
    location: 'Новосибирск',
    employment_type: 'full_time',
    level: 'mid',
    status: 'active',
    applications_count: 6,
    views_count: 145,
    created_at: '2024-02-14',
    updated_at: '2024-02-16',
    deadline: '2024-03-14',
  },
  {
    id: 'vacancy-5',
    company_id: 'company-5',
    title: 'UI/UX дизайнер',
    description:
      'Создавайте красивые и интуитивные интерфейсы пользователя для наших цифровых продуктов. Требуется опыт в Figma и сильное портфолио.',
    salary_min: 80000,
    salary_max: 120000,
    currency: 'RUB',
    location: 'Екатеринбург',
    employment_type: 'full_time',
    level: 'mid',
    status: 'active',
    applications_count: 9,
    views_count: 267,
    created_at: '2024-02-09',
    updated_at: '2024-02-16',
    deadline: '2024-03-09',
  },
  {
    id: 'vacancy-6',
    company_id: 'company-1',
    title: 'Backend разработчик',
    description:
      'Разрабатывайте надежные backend сервисы с использованием Node.js и Express. Требуется опыт работы с PostgreSQL и MongoDB.',
    salary_min: 110000,
    salary_max: 150000,
    currency: 'RUB',
    location: 'Москва',
    employment_type: 'full_time',
    level: 'mid',
    status: 'active',
    applications_count: 10,
    views_count: 198,
    created_at: '2024-02-11',
    updated_at: '2024-02-16',
    deadline: '2024-03-11',
  },
  {
    id: 'vacancy-7',
    company_id: 'company-2',
    title: 'DevOps инженер',
    description:
      'Управляйте и оптимизируйте нашу облачную инфраструктуру. Требуется опыт Docker, Kubernetes и CI/CD конвейеров.',
    salary_min: 125000,
    salary_max: 165000,
    currency: 'RUB',
    location: 'Санкт-Петербург',
    employment_type: 'full_time',
    level: 'senior',
    status: 'active',
    applications_count: 7,
    views_count: 156,
    created_at: '2024-02-13',
    updated_at: '2024-02-16',
    deadline: '2024-03-13',
  },
  {
    id: 'vacancy-8',
    company_id: 'company-3',
    title: 'Data Scientist',
    description:
      'Анализируйте большие наборы данных и создавайте предиктивные модели. Требуется знание Python, R и статистики.',
    salary_min: 115000,
    salary_max: 155000,
    currency: 'RUB',
    location: 'Москва',
    employment_type: 'full_time',
    level: 'mid',
    status: 'active',
    applications_count: 11,
    views_count: 234,
    created_at: '2024-02-07',
    updated_at: '2024-02-16',
    deadline: '2024-03-07',
  },
]

export const mockResumes: Resume[] = [
  {
    id: 'resume-1',
    user_id: 'user-1',
    title: 'Senior Full Stack Developer',
    content: `
Professional Summary: Experienced full stack developer with 8+ years in web development.
Skills: React, Node.js, TypeScript, PostgreSQL, AWS, Docker
Experience: 
- Senior Developer at TechCorp (2021-Present)
- Full Stack Developer at StartupXYZ (2019-2021)
- Junior Developer at WebAgency (2016-2019)
Education: B.S. in Computer Science from State University
    `,
    is_public: true,
    is_primary: true,
    created_at: '2024-01-15',
    updated_at: '2024-02-10',
  },
  {
    id: 'resume-2',
    user_id: 'user-1',
    title: 'Frontend Developer',
    content: `
Professional Summary: Specialized in modern frontend development.
Skills: React, Vue.js, CSS, JavaScript, Webpack, Tailwind
Experience:
- Lead Frontend Developer at DesignCorp (2020-Present)
- Frontend Developer at WebStudio (2018-2020)
Education: Bootcamp Graduate in Web Development
    `,
    is_public: true,
    is_primary: false,
    created_at: '2024-02-01',
    updated_at: '2024-02-10',
  },
]

export const mockJobSeekers: JobSeeker[] = [
  {
    id: 'seeker-1',
    user_id: 'user-1',
    first_name: 'John',
    last_name: 'Developer',
    phone: '+1-555-0100',
    location: 'San Francisco, CA',
    bio: 'Passionate full-stack developer with expertise in modern web technologies.',
    resume_count: 2,
    rating: 4.8,
    created_at: '2024-01-10',
    updated_at: '2024-02-16',
  },
]

export const mockApplications: Application[] = [
  {
    id: 'app-1',
    user_id: 'user-1',
    vacancy_id: 'vacancy-1',
    resume_id: 'resume-1',
    status: 'pending',
    cover_letter: 'I am very interested in this Senior React Developer position...',
    created_at: '2024-02-14',
    updated_at: '2024-02-16',
  },
  {
    id: 'app-2',
    user_id: 'user-1',
    vacancy_id: 'vacancy-3',
    resume_id: 'resume-1',
    status: 'reviewing',
    cover_letter: 'With my ML background, I believe I can contribute significantly...',
    created_at: '2024-02-12',
    updated_at: '2024-02-15',
  },
]
